services:
  db:
    image: mysql:8.0-bookworm
    container_name: smart40n1_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PSWD}
    ports:
      - "3307:3306" # Mapeia a porta 3306 do container para a porta 3307 do host, para evitar conflitos
    volumes:
      - db_data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
    container_name: smart40n1_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000

volumes:
  db_data:
