services:
  app:
    build: .
    image: smart40n1_app_image
    container_name: smart40n1_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: fastapi run
